TARGET_DATARMNET_EXT_ENABLE := false

ifeq ($(TARGET_KERNEL_DLKM_DISABLE), true)
	ifeq ($(TARGET_KERNEL_DLKM_DATARMNETEXT_OVERRIDE), true)
		TARGET_DATARMNET_EXT_ENABLE := true
	endif
else
	TARGET_DATARMNET_EXT_ENABLE := true
endif

ifeq ($(TARGET_DATARMNET_EXT_ENABLE), true)
	#Build rmnet modules
	DATA_OFFLOAD_DLKM_BOARD_PLATFORMS_LIST := sun
	DATA_OFFLOAD_DLKM_BOARD_PLATFORMS_LIST += canoe
        DATA_OFFLOAD_DLKM_BOARD_PLATFORMS_LIST += vienna
        DATA_OFFLOAD_DLKM_BOARD_PLATFORMS_LIST += lahaina
	DATA_OFFLOAD_DLKM_BOARD_PLATFORMS_LIST += chora
	DATA_OFFLOAD_DLKM_BOARD_PLATFORMS_LIST += malabar
	DATA_SHS_DLKM_BOARD_PLATFORMS_LIST := sun
	DATA_SHS_DLKM_BOARD_PLATFORMS_LIST += canoe
        DATA_SHS_DLKM_BOARD_PLATFORMS_LIST += vienna
        DATA_SHS_DLKM_BOARD_PLATFORMS_LIST += lahaina
	DATA_SHS_DLKM_BOARD_PLATFORMS_LIST += chora
	DATA_SHS_DLKM_BOARD_PLATFORMS_LIST += malabar
	DATA_APS_DLKM_BOARD_PLATFORMS_LIST := sun
	DATA_APS_DLKM_BOARD_PLATFORMS_LIST += canoe
        DATA_APS_DLKM_BOARD_PLATFORMS_LIST += vienna
	DATA_APS_DLKM_BOARD_PLATFORMS_LIST += chora
	DATA_APS_DLKM_BOARD_PLATFORMS_LIST += malabar
	DATA_WLAN_DLKM_BOARD_PLATFORMS_LIST := sun
	DATA_WLAN_DLKM_BOARD_PLATFORMS_LIST += canoe
	DATA_WLAN_DLKM_BOARD_PLATFORMS_LIST += vienna
	DATA_WLAN_DLKM_BOARD_PLATFORMS_LIST += monaco
        DATA_WLAN_DLKM_BOARD_PLATFORMS_LIST += lahaina
	DATA_WLAN_DLKM_BOARD_PLATFORMS_LIST += bengal
	DATA_WLAN_DLKM_BOARD_PLATFORMS_LIST += chora
	DATA_WLAN_DLKM_BOARD_PLATFORMS_LIST += malabar
	DATA_MEM_DLKM_BOARD_PLATFORMS_LIST := sun
	DATA_MEM_DLKM_BOARD_PLATFORMS_LIST += canoe
	DATA_MEM_DLKM_BOARD_PLATFORMS_LIST += vienna
	DATA_MEM_DLKM_BOARD_PLATFORMS_LIST += monaco
        DATA_MEM_DLKM_BOARD_PLATFORMS_LIST += lahaina
	DATA_MEM_DLKM_BOARD_PLATFORMS_LIST += bengal
	DATA_MEM_DLKM_BOARD_PLATFORMS_LIST += chora
	DATA_MEM_DLKM_BOARD_PLATFORMS_LIST += malabar

	ifneq ($(TARGET_BOARD_AUTO),true)
		ifneq (,$(call is-board-platform-in-list2,$(DATA_OFFLOAD_DLKM_BOARD_PLATFORMS_LIST)))
			BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/rmnet_offload.ko
			BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/rmnet_perf_tether.ko
			BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/rmnet_perf.ko
			BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/rmnet_wlan.ko
		endif
		ifneq (,$(call is-board-platform-in-list2,$(DATA_MEM_DLKM_BOARD_PLATFORMS_LIST)))
			BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/rmnet_mem.ko
		endif
		ifneq (,$(call is-board-platform-in-list2,$(DATA_SHS_DLKM_BOARD_PLATFORMS_LIST)))
			BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/rmnet_shs.ko
		endif
		ifneq (,$(call is-board-platform-in-list2,$(DATA_APS_DLKM_BOARD_PLATFORMS_LIST)))
			BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/rmnet_aps.ko
			BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/rmnet_sch.ko
		endif
		ifneq (,$(call is-board-platform-in-list2,$(DATA_WLAN_DLKM_BOARD_PLATFORMS_LIST)))
			BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/rmnet_wlan.ko
		endif
	endif
endif
