load(":define_aps.bzl", "define_aps")
load("//build/kernel/kleaf:kernel.bzl", "ddk_headers", "ddk_module")

define_aps("sun", "consolidate")
define_aps("sun", "perf")

define_aps("canoe", "consolidate")
define_aps("canoe", "perf")

define_aps("vienna", "consolidate")
define_aps("vienna", "perf")

define_aps("chora", "consolidate")
define_aps("chora", "perf")

define_aps("malabar", "consolidate")
define_aps("malabar", "perf")

ddk_headers(
    name = "rmnet_aps_include_headers",
    hdrs = glob([
        "include/linux/*.h",
    ]),
    includes = [
        "include",
        "include/linux",
    ],
)

ddk_headers(
    name = "rmnet_aps_uapi_include_headers",
    hdrs = glob([
        "include/uapi/linux/*.h",
    ]),
    includes = [
        "include/uapi",
    ],
)

ddk_headers(
    name = "include_headers",
    hdrs = [
        ":rmnet_aps_include_headers",
        ":rmnet_aps_uapi_include_headers",
    ],
)
